export const ACTIVITY_ENTITY = {
  CONTACT: "CONTACT",
  GROUP: "GROUP",
  CAMPAIGN: "CAMPAIGN",
  WORKSPACE: "WORKSPACE",
  MEMBER: "MEMBER",
  INVITATION: "INVITATION",
} as const;

export const ACTIVITY_ACTION = {
  CONTACT_CREATED: "CONTACT_CREATED",
  CONTACT_UPDATED: "CONTACT_UPDATED",
  CONTACT_DELETED: "CONTACT_DELETED",
  CONTACT_AUTHORIZATION_CHANGED: "CONTACT_AUTHORIZATION_CHANGED",
  CONTACT_AUTHORIZATION_BULK_CHANGED: "CONTACT_AUTHORIZATION_BULK_CHANGED",
  CONTACTS_IMPORTED: "CONTACTS_IMPORTED",
  GROUP_CREATED: "GROUP_CREATED",
  GROUP_UPDATED: "GROUP_UPDATED",
  GROUP_DELETED: "GROUP_DELETED",
  GROUP_MEMBERS_ADDED: "GROUP_MEMBERS_ADDED",
  GROUP_MEMBERS_REMOVED: "GROUP_MEMBERS_REMOVED",
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  CAMPAIGN_READY: "CAMPAIGN_READY",
  CAMPAIGN_SEND_STARTED: "CAMPAIGN_SEND_STARTED",
  CAMPAIGN_COMPLETED: "CAMPAIGN_COMPLETED",
  CAMPAIGN_PARTIAL: "CAMPAIGN_PARTIAL",
  CAMPAIGN_FAILED: "CAMPAIGN_FAILED",
  WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  MEMBER_PERMISSION_CHANGED: "MEMBER_PERMISSION_CHANGED",
  MEMBER_PERMISSIONS_RESET: "MEMBER_PERMISSIONS_RESET",
  MEMBER_SCOPE_CHANGED: "MEMBER_SCOPE_CHANGED",
  INVITATION_CREATED: "INVITATION_CREATED",
  INVITATION_RESENT: "INVITATION_RESENT",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
} as const;

export type ActivityEntityType = typeof ACTIVITY_ENTITY[keyof typeof ACTIVITY_ENTITY];
export type ActivityAction = typeof ACTIVITY_ACTION[keyof typeof ACTIVITY_ACTION];

export const ACTIVITY_FILTERS = {
  all: null,
  contactos: ACTIVITY_ENTITY.CONTACT,
  grupos: ACTIVITY_ENTITY.GROUP,
  campanas: ACTIVITY_ENTITY.CAMPAIGN,
  equipo: ACTIVITY_ENTITY.MEMBER,
  invitaciones: ACTIVITY_ENTITY.INVITATION,
  configuracion: ACTIVITY_ENTITY.WORKSPACE,
} as const;

export type ActivityFilter = keyof typeof ACTIVITY_FILTERS;
